# Res-net model

In [1]:
# ==== Standard Libraries ====
import os, time, warnings

# ==== Scientific & Data Handling ====
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ==== PyTorch Core ====
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import torchvision.transforms as T
from torchvision.models import resnet18

# ==== ML & Evaluation ====
from sklearn.model_selection import train_test_split, GroupShuffleSplit
from sklearn.metrics import (
    confusion_matrix, classification_report, f1_score,
    accuracy_score, balanced_accuracy_score, roc_auc_score, recall_score
)
from sklearn.utils import resample
from statsmodels.stats.proportion import proportions_ztest

# ==== Utilities ====
from tqdm import tqdm

# ==== Reproducibility ====
SEED = 42

# ==== Device Handling (DirectML + fallback CPU) ====
try:
    import torch_directml
    DEVICE = torch_directml.device()
    print("Using DirectML device:", DEVICE)
except Exception as e:
    DEVICE = torch.device("cpu")
    print("DirectML no disponible. Usando CPU:", e)

# ==== Warnings ====
warnings.filterwarnings('ignore')

Using DirectML device: privateuseone:0


In [2]:
CSV_PATH = '../Data/Tabular.csv'
FOLDER_PATH = r"C:\Users\usuario\MRI\IMAGES_npy"

OUTPUT_DIR = "../Models_Output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

In [3]:
# [] Atributos de las imégenes
shapes, means, stds, size = [], [], [], []

for f in os.listdir(FOLDER_PATH):
    if f.endswith(".npy"):
        img = np.load(os.path.join(FOLDER_PATH, f))
        shapes.append(img.shape)
        means.append(img.mean())
        stds.append(img.std())
        size.append(img.size)

# Contar shapes únicos
shapes_unicos = set(shapes)
size_unicos = set(size)
print("Shapes únicos encontrados:", shapes_unicos)
print("Total de imágenes:", len(shapes))
print(f"Media global promedio: {np.mean(means):.4f}")
print(f"Desviación global promedio: {np.mean(stds):.4f}")
print(f"Size únicos: {size_unicos}")

Shapes únicos encontrados: {(160, 192, 192)}
Total de imágenes: 220
Media global promedio: 0.0000
Desviación global promedio: 1.0000
Size únicos: {5898240}


In [4]:
# LOAD CSV
# ============================
df = pd.read_csv(CSV_PATH, dtype={'sujeto_id': str})
df = df.dropna(subset=['is_dementia'])

df['sujeto_id'] = df['sujeto_id'].astype(str).str.strip()
df['imagen_id'] = df['imagen_id'].astype(str).str.strip()

# FULL FILE PATH
def build_path(row):
    filename = f"{row['sujeto_id']}_{row['imagen_id']}.npy"
    return os.path.join(FOLDER_PATH, filename)

df['file_path'] = df.apply(build_path, axis=1)

df = df[['file_path', 'sujeto_id', 'is_dementia']].rename(
    columns={'is_dementia': 'label'}
)


In [5]:
# 1. Distribución básica de is_dementia

class_distribution = df['label'].value_counts().sort_index()
print("=== DISTRIBUCIÓN DE CLASES ===")
print(f"Clase 0 (No Dementia): {class_distribution.get(0, 0)} imágenes - {class_distribution.get(0, 0)/len(df)*100:.2f}%")
print(f"Clase 1 (Dementia): {class_distribution.get(1, 0)} imágenes - {class_distribution.get(1, 0)/len(df)*100:.2f}%")
class_distribution = df['label'].value_counts().sort_index()
N = len(df)
count_dementia = class_distribution.get(1, 0)
expected_proportion = 0.5 
z_stat, p_value = proportions_ztest(count=count_dementia, 
                                    nobs=N, 
                                    value=expected_proportion, 
                                    alternative='two-sided')
print(f"Estadístico Z: {z_stat:.4f}")
print(f"Valor p: {p_value:.4e}")
# Conclusión
alpha = 0.05
if p_value < alpha:
    print(f"\nConclusión: Se rechaza H0. La proporción de la Clase 1 ({count_dementia/N*100:.2f}%) es SIGNIFICATIVAMENTE diferente de {expected_proportion*100:.0f}%.")
else:
    print(f"\nConclusión: No se rechaza H0. No hay evidencia suficiente para decir que la proporción es diferente de {expected_proportion*100:.0f}%.")

=== DISTRIBUCIÓN DE CLASES ===
Clase 0 (No Dementia): 158 imágenes - 71.82%
Clase 1 (Dementia): 62 imágenes - 28.18%
Estadístico Z: -7.1933
Valor p: 6.3244e-13

Conclusión: Se rechaza H0. La proporción de la Clase 1 (28.18%) es SIGNIFICATIVAMENTE diferente de 50%.


In [6]:
def group_stratified_split(records):
    """
    Split estratificado por SUJETO:
        Train 60%
        Val   20%
        Test  20%
    Sin fuga de información.
    """

    df_local = pd.DataFrame(records)

    # 1. Etiqueta por sujeto (promedio -> entero)
    subj_lab = df_local.groupby("sujeto_id")["label"].agg(lambda x: int(round(x.mean())))
    subjects = subj_lab.index.to_list()
    y = subj_lab.values

    # -----------------------------
    # 2. Train (60%) vs Resto (40%)
    # -----------------------------
    gss1 = GroupShuffleSplit(n_splits=1, train_size=0.6, random_state=SEED)
    train_idx, rest_idx = next(gss1.split(subjects, y, groups=subjects))

    train_subj = [subjects[i] for i in train_idx]
    rest_subj  = [subjects[i] for i in rest_idx]

    # -----------------------------
    # 3. Val (20%) vs Test (20%) dentro del 40%
    # -----------------------------
    rest_labels = [subj_lab[s] for s in rest_subj]

    val_subj, test_subj = train_test_split(
        rest_subj,
        test_size=0.5,
        random_state=SEED,
        stratify=rest_labels
    )

    # -----------------------------
    # 4. Regresar DataFrames
    # -----------------------------
    def pick(subjects_list):
        return df_local[df_local["sujeto_id"].isin(subjects_list)].reset_index(drop=True)

    return pick(train_subj), pick(val_subj), pick(test_subj)


In [7]:
# [PASO 2] Construcción del DataSet MRI 2.5D
# ---------------------------

class MRI2p5DDataset(Dataset):
    def __init__(self, df, n_slices, target_size=(224,224), augment=False):
        """
        df: DataFrame con columnas 'file_path' y 'label'
        n_slices: número de cortes a tomar por volumen
        target_size: tamaño HxW de las imágenes
        augment: aplicar data augmentation
        """
        self.records = df.to_dict("records")
        self.n_slices = n_slices
        self.target_size = target_size
        self.augment = augment

        # Transforms
        self.augment_tf = T.Compose([
            T.RandomRotation(10),
            T.RandomResizedCrop(target_size, scale=(0.9,1.0))
        ])
        self.base_tf = T.Compose([
            T.Resize(target_size),
            T.ToTensor()
        ])
        
    def __len__(self):
        return len(self.records)
    
    def __getitem__(self, idx):
        rec = self.records[idx]
        vol = np.load(rec["file_path"])  # (D,H,W) 3D array, Cortes-Altura-Ancho

        # Elegir n_slices uniformemente
        D = vol.shape[0]
        idxs = np.linspace(0, D-1, self.n_slices).astype(int)
        slices = vol[idxs]  # (n_slices,H,W)

        # Convertir cada slice a tensor
        imgs = []
        for s in slices:
            # Normalizar a [0,255] y convertir a PIL
            s_img = ((s - s.min())/(s.max()-s.min()+1e-6) * 255).astype(np.uint8)
            img = Image.fromarray(s_img).convert("L")  # 1 canal
            if self.augment:
                img = self.augment_tf(img)
            img = self.base_tf(img)  # (1,H,W)
            imgs.append(img)
        
        # Apilar slices como canales -> (n_slices,H,W)
        input_tensor = torch.cat(imgs, dim=0)
        
        label = torch.tensor(rec["label"], dtype=torch.float32)
        return input_tensor, label

In [8]:
# [PASO 3] Modelo ResNet18 MRI 2.5D
# ---------------------------

class ResNet18_2p5D(nn.Module):
    """
    Modelo 2.5D basado en ResNet18 para clasificación binaria de volúmenes 3D (MRI). 
    
    Idea clave:
    - Cada volumen 3D se divide en 'n_slices' cortes (slices) uniformes.
    - Los slices se apilan como canales de una imagen 2D de entrada.
    - La ResNet18 procesa todos los slices simultáneamente como una "imagen 2D con n_slices canales".
    - La salida es un logit único por volumen, útil para predecir probabilidad de progresión de Alzheimer.

    Parámetros
    ----------
    n_slices : int
        Número de cortes (slices) que se apilan como canales de entrada.
        Por defecto: 32.
    """

    def __init__(self, n_slices):
        super().__init__()

        # Base ResNet18 sin pesos preentrenados
        self.model = resnet18(weights=None)
        self.model.conv1 = nn.Conv2d(
            in_channels=n_slices,
            out_channels=64,
            kernel_size=7,
            stride=2,
            padding=3,
            bias=False
        )
        self.model.fc = nn.Sequential(
            nn.Dropout(0.3),
            nn.Linear(512,1)
        )

    def forward(self, x):
        """
        Forward pass del modelo.

        Parámetros
        ----------
        x : torch.Tensor
            Tensor de entrada de forma (B, n_slices, H, W)
            donde B = batch size, n_slices = número de slices apilados,
            H y W = dimensiones espaciales de cada slice.

        Retorna
        -------
        logits : torch.Tensor
            Tensor de forma (B,), logit único por volumen.
            Este logit se puede pasar a sigmoid para obtener probabilidad.
        """
        # x: (B, n_slices, H, W)
        logits = self.model(x)  # ResNet18 produce (B,1)
        return logits.squeeze(1)  # Redimensiona a (B,)


In [9]:
# [PASO 4] Entrenamiento por epoca y evaluacion
# ---------------------------

def train_epoch(model, loader, criterion, optimizer, device):
    model.train()                    # Coloca el modelo en modo entrenamiento
    total_loss = 0
    total = 0
    pbar = tqdm(loader, desc="Train", leave=False)
    
    for X, y in pbar:
        X, y = X.to(device), y.to(device)  # Enviar batch a GPU/CPU
        optimizer.zero_grad()              # Reiniciar gradientes

        logits = model(X)                  # Forward
        loss = criterion(logits, y)        # Calcular pérdida
        loss.backward()                     # Backpropagation
        optimizer.step()                    # Actualizar pesos

        total_loss += loss.item() * y.size(0)  # Acumular pérdida ponderada por batch
        total += y.size(0)
        pbar.set_postfix({"batch_loss": loss.item()})  # Mostrar pérdida por batch

    return total_loss / total  # Pérdida promedio por sample

def evaluate(model, val_loader, device):
    model.eval()
    all_labels = []
    all_preds = []
    all_probs = []

    with torch.no_grad():
        for images, labels in val_loader:
            images = images.to(device)
            labels = labels.float().to(device)

            logits = model(images)
            prob = torch.sigmoid(logits).cpu().numpy().flatten()
            pred = (prob >= 0.5).astype(int)

            all_labels.extend(labels.cpu().numpy())
            all_preds.extend(pred)
            all_probs.extend(prob)

    acc = accuracy_score(all_labels, all_preds)
    bal_acc = balanced_accuracy_score(all_labels, all_preds)
    auc = roc_auc_score(all_labels, all_probs)
    recall = recall_score(all_labels, all_preds)

    return acc, bal_acc, auc, recall


In [10]:
def prepare_dataloaders(df, batch_size, n_slices, target_size=(224,224)):
    records = df.to_dict("records")

    # -------- SPLIT POR SUJETO (60/20/20) --------
    train_df, val_df, test_df = group_stratified_split(records)

    #print(f"Dimensiones: Train {len(train_df)} | Val {len(val_df)} | Test {len(test_df)}")

    # ========== CALCULAR CLASE PREDOMINANTE POR SUJETO ==========
    subj_lab = train_df.groupby("sujeto_id")["label"].agg(lambda x: int(round(x.mean())))

    #print("\n=== Etiqueta predominante por sujeto (Train) ===")
    #print(subj_lab.value_counts())

    # Sujetos mayoritarios/minoritarios según la etiqueta predominante
    maj_subj = subj_lab[subj_lab == 0].index.tolist()
    min_subj = subj_lab[subj_lab == 1].index.tolist()

    #print(f"Sujetos clase 0 (majority): {len(maj_subj)}")
    #print(f"Subjects clase 1 (minority): {len(min_subj)}")

    # ========== UPSAMPLING A NIVEL DE SUJETO ==========
    min_subj_upsampled = resample(
        min_subj,
        replace=True,
        n_samples=len(maj_subj),
        random_state=42
    )

    #print("\nSujetos repetidos en oversampling:")
    #print(pd.Series(min_subj_upsampled).value_counts())

    # ========== RECONSTRUIR TRAIN BALANCEADO SIN MODIFICAR VISITAS ==========
    train_df_bal = pd.concat([
        train_df[train_df["sujeto_id"].isin(maj_subj)],
        train_df[train_df["sujeto_id"].isin(min_subj_upsampled)]
    ]).sample(frac=1, random_state=42)

    #print("\n=== Distribución después de oversampling (por imagen) ===")
    #print(train_df_bal["label"].value_counts())

    # ========== DATASETS ==========
    train_dataset = MRI2p5DDataset(train_df_bal, n_slices=n_slices,
                                   target_size=target_size, augment=True)
    val_dataset   = MRI2p5DDataset(val_df, n_slices=n_slices,
                                   target_size=target_size, augment=False)
    test_dataset  = MRI2p5DDataset(test_df, n_slices=n_slices,
                                   target_size=target_size, augment=False)

    # ========== DATALOADERS ==========
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader   = DataLoader(val_dataset, batch_size=batch_size)
    test_loader  = DataLoader(test_dataset, batch_size=batch_size)

    #print(f"\nTrain Loader: {len(train_loader.dataset)} ejemplos, {len(train_loader)} batches")
    #print(f"Validation Loader: {len(val_loader.dataset)} ejemplos, {len(val_loader)} batches")
    #print(f"Test Loader: {len(test_loader.dataset)} ejemplos, {len(test_loader)} batches")

    return train_loader, val_loader, test_loader


In [11]:
# [PASO 6] Modulo de entrenamiento
# ---------------------------
def train_model(
        model, train_loader, val_loader, device, 
        epochs, lr, weight_decay, early_stopping_patience, model_ej):
    """
    Entrena el modelo y retorna listas de pérdidas y métricas.
    """
    print(f"\n⏺️ Épocas {epochs} | LR-WD {lr}-{ weight_decay} | Patience {early_stopping_patience}")

    criterion = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3, verbose=True)

    train_losses, val_recalls, val_aucs, val_bac = [], [], [], []
    best_bal_acc = 0
    patience_counter = 0

    print("▶️ Start train")
    time_all = time.time()

    for ep in range(epochs):
        time_ep = time.time()
        train_loss = train_epoch(model, train_loader, criterion, optimizer, device)
        time_train = time.time() - time_ep
        acc, bal_acc, auc, recall = evaluate(model, val_loader, device)
        
        train_losses.append(train_loss)
        val_recalls.append(recall)
        val_aucs.append(auc)
        val_bac.append(bal_acc)

        #print(f"Epoch {ep+1}/{epochs} | TrainLoss={train_loss:.4f} ||"
           #   f"BAC ={bal_acc:.4f} | Recall ={recall:.4f} | "
           #   f"AUC={auc:.4f} | Time={time_train/60:.2f}")
        # Scheduler
        scheduler.step(train_loss)

        # EARLY STOPPING usando RECALL DE LA CLASE 1
        if bal_acc > best_bal_acc:  # Considera ambas clases
            best_bal_acc = bal_acc
            patience_counter = 0
            model_path = f"../Models_Output_2/{model_ej}_{epochs}_{ep}_{early_stopping_patience}.pth"
            torch.save(model.state_dict(), model_path)
            print(f">> Mejor modelo guardado"
                  f"Epoch {ep+1}/{epochs} | TrainLoss={train_loss:.4f} ||"
                  f"BAC ={bal_acc:.4f} | Recall ={recall:.4f} | "
                  f"AUC={auc:.4f}")
        else:
            patience_counter += 1
            if patience_counter >= early_stopping_patience:
                print(f">> Early stopping activado {ep}")
                break

    
    print(f"Tiempo total de entrenamiento: {(time.time() - time_all)/60:.2f} minutos")
    return train_losses, val_bac, val_aucs, model_path

In [12]:
def evaluate_final(model, test_loader, device, model_path):
    """
    Evalúa el mejor modelo guardado y calcula métricas relevantes,
    incluyendo sensibilidad (recall de clase positiva) y especificidad.
    """
    print(f"Best model: {model_path}")
    model.load_state_dict(torch.load(model_path))
    model.eval()

    all_preds, all_labels = [], []

    with torch.no_grad():
        for X, y in test_loader:
            X, y = X.to(device), y.to(device)
            logits = model(X)
            probs = torch.sigmoid(logits)
            preds = (probs > 0.5).float()
            all_preds.append(preds.cpu())
            all_labels.append(y.cpu())

    all_preds = torch.cat(all_preds)
    all_labels = torch.cat(all_labels)

    acc = (all_preds == all_labels).float().mean().item()
    bal_acc = balanced_accuracy_score(all_labels, all_preds)

    try:
        auc = roc_auc_score(all_labels, all_preds)
    except ValueError:
        auc = float('nan')

    recall = recall_score(all_labels, all_preds)
    f1 = f1_score(all_labels, all_preds)

    print(f"\n TEST =====")

    print(f"BAC = {bal_acc:.4f} | AUC = {auc:.4f} | recall = {recall:.4f}  | f1 = {f1:.4f}")
    # Matriz de confusión
    cm = confusion_matrix(all_labels, all_preds)
    print("\nMatriz de confusión:")
    print(cm)

    # Reporte de clasificación
    report = classification_report(all_labels, all_preds, target_names=["No Dementia", "Dementia"])
    print("\nReporte de clasificación:")
    print(report)

    return acc, bal_acc, auc, recall, f1, cm, report


In [13]:
# ---------------------------
# MAIN
# ---------------------------
def main(df, device, n_slices, EPOCHS, LR, WEIGHT, EARLY, BATCH, MODELO):
    print(F"✳️ Entrenando modelo {MODELO}")
    train_loader, val_loader, test_loader = prepare_dataloaders(df, BATCH, n_slices)

    model = ResNet18_2p5D(n_slices).to(device)
    
    train_losses, val_bac, val_aucs, model_path = train_model(
        model, train_loader, val_loader, device, 
        EPOCHS, LR, WEIGHT, EARLY, MODELO)
        
    # Evaluación final
    evaluate_final(model, test_loader, device, model_path)


-----------------

In [16]:
import itertools

# Definir los rangos de LR y WEIGHT
LR_RANGE = [1e-3, 8e-4, 6e-4, 5e-4]
WEIGHT_RANGE = [1e-3, 8e-4, 6e-4, 5e-4]

# Crear todas las combinaciones posibles (16 en total)
grid = list(itertools.product(LR_RANGE, WEIGHT_RANGE))

## 30 epocas, batch 8

In [ ]:
# Ejecutar 1
EPOCHS = 30
EARLY = 5
n_slices = 64
BATCH = 8
# ---------------------------
# Ejecutar cada combinación
for i, (LR, WEIGHT) in enumerate(grid, start=1):
    MODELO = f"Ejex_{i}_{n_slices}_{BATCH}"
    main(df, DEVICE, n_slices, EPOCHS, LR, WEIGHT, EARLY, BATCH, MODELO)

✳️ Entrenando modelo Ejex_1_64_8

⏺️ Épocas 30 | LR-WD 0.001-0.001 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.8530 ||BAC =0.5000 | Recall =1.0000 | AUC=0.5172


>> Mejor modelo guardadoEpoch 2/30 | TrainLoss=0.6390 ||BAC =0.5948 | Recall =0.5000 | AUC=0.6069


>> Early stopping activado 6
Tiempo total de entrenamiento: 3.91 minutos
Best model: ../Models_Output_2/Ejex_1_64_8_30_1_5.pth

 TEST =====
BAC = 0.6750 | AUC = 0.6750 | recall = 0.6000  | f1 = 0.3000

Matriz de confusión:
[[36 12]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.95      0.75      0.84        48
    Dementia       0.20      0.60      0.30         5

    accuracy                           0.74        53
   macro avg       0.57      0.68      0.57        53
weighted avg       0.88      0.74      0.79        53

✳️ Entrenando modelo Ejex_2_64_8

⏺️ Épocas 30 | LR-WD 0.001-0.0008 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.9673 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5483


>> Mejor modelo guardadoEpoch 2/30 | TrainLoss=0.7481 ||BAC =0.5500 | Recall =0.1000 | AUC=0.5966


>> Mejor modelo guardadoEpoch 5/30 | TrainLoss=0.5976 ||BAC =0.6052 | Recall =0.9000 | AUC=0.3828


>> Early stopping activado 9
Tiempo total de entrenamiento: 4.87 minutos
Best model: ../Models_Output_2/Ejex_2_64_8_30_4_5.pth

 TEST =====
BAC = 0.5625 | AUC = 0.5625 | recall = 1.0000  | f1 = 0.1923

Matriz de confusión:
[[ 6 42]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.12      0.22        48
    Dementia       0.11      1.00      0.19         5

    accuracy                           0.21        53
   macro avg       0.55      0.56      0.21        53
weighted avg       0.92      0.21      0.22        53

✳️ Entrenando modelo Ejex_3_64_8

⏺️ Épocas 30 | LR-WD 0.001-0.0006 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.8100 ||BAC =0.4500 | Recall =0.9000 | AUC=0.3586


>> Mejor modelo guardadoEpoch 2/30 | TrainLoss=0.6700 ||BAC =0.4569 | Recall =0.5000 | AUC=0.3793


>> Mejor modelo guardadoEpoch 4/30 | TrainLoss=0.6221 ||BAC =0.4638 | Recall =0.1000 | AUC=0.5931


>> Mejor modelo guardadoEpoch 5/30 | TrainLoss=0.4769 ||BAC =0.4759 | Recall =0.4000 | AUC=0.4155


>> Mejor modelo guardadoEpoch 6/30 | TrainLoss=0.6624 ||BAC =0.4828 | Recall =0.0000 | AUC=0.3414


>> Mejor modelo guardadoEpoch 8/30 | TrainLoss=0.5787 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5034


>> Early stopping activado 12
Tiempo total de entrenamiento: 21.83 minutos
Best model: ../Models_Output_2/Ejex_3_64_8_30_7_5.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_4_64_8

⏺️ Épocas 30 | LR-WD 0.001-0.0005 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.8491 ||BAC =0.5000 | Recall =0.0000 | AUC=0.7276


>> Early stopping activado 5
Tiempo total de entrenamiento: 3.02 minutos
Best model: ../Models_Output_2/Ejex_4_64_8_30_0_5.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_5_64_8

⏺️ Épocas 30 | LR-WD 0.0008-0.001 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7954 ||BAC =0.4069 | Recall =0.4000 | AUC=0.3483


>> Mejor modelo guardadoEpoch 2/30 | TrainLoss=0.6587 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4586


>> Mejor modelo guardadoEpoch 4/30 | TrainLoss=0.6549 ||BAC =0.6414 | Recall =0.8000 | AUC=0.5655


>> Early stopping activado 8
Tiempo total de entrenamiento: 4.71 minutos
Best model: ../Models_Output_2/Ejex_5_64_8_30_3_5.pth

 TEST =====
BAC = 0.6396 | AUC = 0.6396 | recall = 0.8000  | f1 = 0.2353

Matriz de confusión:
[[23 25]
 [ 1  4]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.96      0.48      0.64        48
    Dementia       0.14      0.80      0.24         5

    accuracy                           0.51        53
   macro avg       0.55      0.64      0.44        53
weighted avg       0.88      0.51      0.60        53

✳️ Entrenando modelo Ejex_6_64_8

⏺️ Épocas 30 | LR-WD 0.0008-0.0008 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7913 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5690


>> Mejor modelo guardadoEpoch 3/30 | TrainLoss=0.6268 ||BAC =0.5069 | Recall =0.6000 | AUC=0.4241


>> Early stopping activado 7
Tiempo total de entrenamiento: 4.23 minutos
Best model: ../Models_Output_2/Ejex_6_64_8_30_2_5.pth

 TEST =====
BAC = 0.5354 | AUC = 0.5354 | recall = 0.8000  | f1 = 0.1818

Matriz de confusión:
[[13 35]
 [ 1  4]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.93      0.27      0.42        48
    Dementia       0.10      0.80      0.18         5

    accuracy                           0.32        53
   macro avg       0.52      0.54      0.30        53
weighted avg       0.85      0.32      0.40        53

✳️ Entrenando modelo Ejex_7_64_8

⏺️ Épocas 30 | LR-WD 0.0008-0.0006 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.8083 ||BAC =0.4655 | Recall =0.0000 | AUC=0.4034


>> Mejor modelo guardadoEpoch 3/30 | TrainLoss=0.6143 ||BAC =0.5069 | Recall =0.6000 | AUC=0.3862


>> Early stopping activado 7
Tiempo total de entrenamiento: 4.18 minutos
Best model: ../Models_Output_2/Ejex_7_64_8_30_2_5.pth

 TEST =====
BAC = 0.6250 | AUC = 0.6250 | recall = 1.0000  | f1 = 0.2174

Matriz de confusión:
[[12 36]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.25      0.40        48
    Dementia       0.12      1.00      0.22         5

    accuracy                           0.32        53
   macro avg       0.56      0.62      0.31        53
weighted avg       0.92      0.32      0.38        53

✳️ Entrenando modelo Ejex_8_64_8

⏺️ Épocas 30 | LR-WD 0.0008-0.0005 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.8519 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4103


>> Mejor modelo guardadoEpoch 2/30 | TrainLoss=0.6920 ||BAC =0.5138 | Recall =0.2000 | AUC=0.4793


>> Early stopping activado 6
Tiempo total de entrenamiento: 3.66 minutos
Best model: ../Models_Output_2/Ejex_8_64_8_30_1_5.pth

 TEST =====
BAC = 0.7958 | AUC = 0.7958 | recall = 0.8000  | f1 = 0.4211

Matriz de confusión:
[[38 10]
 [ 1  4]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.97      0.79      0.87        48
    Dementia       0.29      0.80      0.42         5

    accuracy                           0.79        53
   macro avg       0.63      0.80      0.65        53
weighted avg       0.91      0.79      0.83        53

✳️ Entrenando modelo Ejex_9_64_8

⏺️ Épocas 30 | LR-WD 0.0006-0.001 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7450 ||BAC =0.4793 | Recall =0.2000 | AUC=0.3828


>> Mejor modelo guardadoEpoch 2/30 | TrainLoss=0.7091 ||BAC =0.5000 | Recall =0.0000 | AUC=0.3828


>> Mejor modelo guardadoEpoch 5/30 | TrainLoss=0.5861 ||BAC =0.5397 | Recall =0.7000 | AUC=0.4379


>> Mejor modelo guardadoEpoch 10/30 | TrainLoss=0.5161 ||BAC =0.5431 | Recall =0.5000 | AUC=0.5517


>> Mejor modelo guardadoEpoch 14/30 | TrainLoss=0.3866 ||BAC =0.5500 | Recall =0.1000 | AUC=0.2552


>> Mejor modelo guardadoEpoch 16/30 | TrainLoss=0.3886 ||BAC =0.5862 | Recall =1.0000 | AUC=0.4552


>> Early stopping activado 20
Tiempo total de entrenamiento: 11.21 minutos
Best model: ../Models_Output_2/Ejex_9_64_8_30_15_5.pth

 TEST =====
BAC = 0.5625 | AUC = 0.5625 | recall = 1.0000  | f1 = 0.1923

Matriz de confusión:
[[ 6 42]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.12      0.22        48
    Dementia       0.11      1.00      0.19         5

    accuracy                           0.21        53
   macro avg       0.55      0.56      0.21        53
weighted avg       0.92      0.21      0.22        53

✳️ Entrenando modelo Ejex_10_64_8

⏺️ Épocas 30 | LR-WD 0.0006-0.0008 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7732 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4414


>> Early stopping activado 5
Tiempo total de entrenamiento: 3.11 minutos
Best model: ../Models_Output_2/Ejex_10_64_8_30_0_5.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_11_64_8

⏺️ Épocas 30 | LR-WD 0.0006-0.0006 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.8176 ||BAC =0.5000 | Recall =1.0000 | AUC=0.5379


>> Early stopping activado 5
Tiempo total de entrenamiento: 3.16 minutos
Best model: ../Models_Output_2/Ejex_11_64_8_30_0_5.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 1.0000  | f1 = 0.1724

Matriz de confusión:
[[ 0 48]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.00      0.00      0.00        48
    Dementia       0.09      1.00      0.17         5

    accuracy                           0.09        53
   macro avg       0.05      0.50      0.09        53
weighted avg       0.01      0.09      0.02        53

✳️ Entrenando modelo Ejex_12_64_8

⏺️ Épocas 30 | LR-WD 0.0006-0.0005 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7712 ||BAC =0.5000 | Recall =1.0000 | AUC=0.5655


>> Mejor modelo guardadoEpoch 5/30 | TrainLoss=0.6369 ||BAC =0.5155 | Recall =0.1000 | AUC=0.6276


>> Mejor modelo guardadoEpoch 7/30 | TrainLoss=0.5839 ||BAC =0.5586 | Recall =0.6000 | AUC=0.4345


>> Early stopping activado 11
Tiempo total de entrenamiento: 6.40 minutos
Best model: ../Models_Output_2/Ejex_12_64_8_30_6_5.pth

 TEST =====
BAC = 0.5917 | AUC = 0.5917 | recall = 0.6000  | f1 = 0.2143

Matriz de confusión:
[[28 20]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.93      0.58      0.72        48
    Dementia       0.13      0.60      0.21         5

    accuracy                           0.58        53
   macro avg       0.53      0.59      0.47        53
weighted avg       0.86      0.58      0.67        53

✳️ Entrenando modelo Ejex_13_64_8

⏺️ Épocas 30 | LR-WD 0.0005-0.001 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7745 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5414


>> Mejor modelo guardadoEpoch 2/30 | TrainLoss=0.6093 ||BAC =0.5569 | Recall =0.7000 | AUC=0.4414


>> Early stopping activado 6
Tiempo total de entrenamiento: 3.63 minutos
Best model: ../Models_Output_2/Ejex_13_64_8_30_1_5.pth

 TEST =====
BAC = 0.3354 | AUC = 0.3354 | recall = 0.4000  | f1 = 0.0952

Matriz de confusión:
[[13 35]
 [ 3  2]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.81      0.27      0.41        48
    Dementia       0.05      0.40      0.10         5

    accuracy                           0.28        53
   macro avg       0.43      0.34      0.25        53
weighted avg       0.74      0.28      0.38        53

✳️ Entrenando modelo Ejex_14_64_8

⏺️ Épocas 30 | LR-WD 0.0005-0.0008 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7709 ||BAC =0.4810 | Recall =0.1000 | AUC=0.4724


>> Mejor modelo guardadoEpoch 2/30 | TrainLoss=0.6766 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4690


>> Early stopping activado 6
Tiempo total de entrenamiento: 3.62 minutos
Best model: ../Models_Output_2/Ejex_14_64_8_30_1_5.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_15_64_8

⏺️ Épocas 30 | LR-WD 0.0005-0.0006 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7858 ||BAC =0.5000 | Recall =1.0000 | AUC=0.4690


>> Early stopping activado 5
Tiempo total de entrenamiento: 3.09 minutos
Best model: ../Models_Output_2/Ejex_15_64_8_30_0_5.pth

 TEST =====
BAC = 0.5104 | AUC = 0.5104 | recall = 1.0000  | f1 = 0.1754

Matriz de confusión:
[[ 1 47]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.02      0.04        48
    Dementia       0.10      1.00      0.18         5

    accuracy                           0.11        53
   macro avg       0.55      0.51      0.11        53
weighted avg       0.91      0.11      0.05        53

✳️ Entrenando modelo Ejex_16_64_8

⏺️ Épocas 30 | LR-WD 0.0005-0.0005 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.9026 ||BAC =0.5810 | Recall =0.3000 | AUC=0.5241


>> Early stopping activado 5
Tiempo total de entrenamiento: 3.10 minutos
Best model: ../Models_Output_2/Ejex_16_64_8_30_0_5.pth

 TEST =====
BAC = 0.4062 | AUC = 0.4062 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[39  9]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.89      0.81      0.85        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.74        53
   macro avg       0.44      0.41      0.42        53
weighted avg       0.80      0.74      0.77        53



## Epochs 20 , batch 8

In [ ]:
# Ejecutar 2
EPOCHS = 20
EARLY = 3
n_slices = 64
BATCH = 8
# ---------------------------
# Ejecutar cada combinación
for i, (LR, WEIGHT) in enumerate(grid, start=1):
    MODELO = f"Ejex_{i}_{n_slices}_{BATCH}"
    main(df, DEVICE, n_slices, EPOCHS, LR, WEIGHT, EARLY, BATCH, MODELO)

✳️ Entrenando modelo Ejex_1_64_8

⏺️ Épocas 20 | LR-WD 0.001-0.001 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.9186 ||BAC =0.5000 | Recall =1.0000 | AUC=0.5345


>> Early stopping activado 3
Tiempo total de entrenamiento: 1.85 minutos
Best model: ../Models_Output_2/Ejex_1_64_8_20_0_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 1.0000  | f1 = 0.1724

Matriz de confusión:
[[ 0 48]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.00      0.00      0.00        48
    Dementia       0.09      1.00      0.17         5

    accuracy                           0.09        53
   macro avg       0.05      0.50      0.09        53
weighted avg       0.01      0.09      0.02        53

✳️ Entrenando modelo Ejex_2_64_8

⏺️ Épocas 20 | LR-WD 0.001-0.0008 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.9557 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5414


>> Mejor modelo guardadoEpoch 2/20 | TrainLoss=0.7043 ||BAC =0.5724 | Recall =0.8000 | AUC=0.6414


>> Early stopping activado 4
Tiempo total de entrenamiento: 2.61 minutos
Best model: ../Models_Output_2/Ejex_2_64_8_20_1_3.pth

 TEST =====
BAC = 0.4250 | AUC = 0.4250 | recall = 0.6000  | f1 = 0.1364

Matriz de confusión:
[[12 36]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.86      0.25      0.39        48
    Dementia       0.08      0.60      0.14         5

    accuracy                           0.28        53
   macro avg       0.47      0.42      0.26        53
weighted avg       0.78      0.28      0.36        53

✳️ Entrenando modelo Ejex_3_64_8

⏺️ Épocas 20 | LR-WD 0.001-0.0006 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8217 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4759


>> Mejor modelo guardadoEpoch 4/20 | TrainLoss=0.5700 ||BAC =0.5414 | Recall =0.6000 | AUC=0.4241


>> Early stopping activado 6
Tiempo total de entrenamiento: 3.63 minutos
Best model: ../Models_Output_2/Ejex_3_64_8_20_3_3.pth

 TEST =====
BAC = 0.6125 | AUC = 0.6125 | recall = 0.6000  | f1 = 0.2308

Matriz de confusión:
[[30 18]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.94      0.62      0.75        48
    Dementia       0.14      0.60      0.23         5

    accuracy                           0.62        53
   macro avg       0.54      0.61      0.49        53
weighted avg       0.86      0.62      0.70        53

✳️ Entrenando modelo Ejex_4_64_8

⏺️ Épocas 20 | LR-WD 0.001-0.0005 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8714 ||BAC =0.5414 | Recall =0.6000 | AUC=0.4517


>> Early stopping activado 3
Tiempo total de entrenamiento: 2.07 minutos
Best model: ../Models_Output_2/Ejex_4_64_8_20_0_3.pth

 TEST =====
BAC = 0.5708 | AUC = 0.5708 | recall = 0.6000  | f1 = 0.2000

Matriz de confusión:
[[26 22]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.93      0.54      0.68        48
    Dementia       0.12      0.60      0.20         5

    accuracy                           0.55        53
   macro avg       0.52      0.57      0.44        53
weighted avg       0.85      0.55      0.64        53

✳️ Entrenando modelo Ejex_5_64_8

⏺️ Épocas 20 | LR-WD 0.0008-0.001 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8487 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4241


>> Mejor modelo guardadoEpoch 2/20 | TrainLoss=0.7621 ||BAC =0.5500 | Recall =0.1000 | AUC=0.4483


>> Early stopping activado 4
Tiempo total de entrenamiento: 2.63 minutos
Best model: ../Models_Output_2/Ejex_5_64_8_20_1_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_6_64_8

⏺️ Épocas 20 | LR-WD 0.0008-0.0008 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8148 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4483


>> Mejor modelo guardadoEpoch 4/20 | TrainLoss=0.5860 ||BAC =0.5379 | Recall =0.8000 | AUC=0.4552


>> Early stopping activado 6
Tiempo total de entrenamiento: 3.71 minutos
Best model: ../Models_Output_2/Ejex_6_64_8_20_3_3.pth

 TEST =====
BAC = 0.4625 | AUC = 0.4625 | recall = 0.8000  | f1 = 0.1569

Matriz de confusión:
[[ 6 42]
 [ 1  4]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.86      0.12      0.22        48
    Dementia       0.09      0.80      0.16         5

    accuracy                           0.19        53
   macro avg       0.47      0.46      0.19        53
weighted avg       0.78      0.19      0.21        53

✳️ Entrenando modelo Ejex_7_64_8

⏺️ Épocas 20 | LR-WD 0.0008-0.0006 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8339 ||BAC =0.5000 | Recall =1.0000 | AUC=0.5483


>> Early stopping activado 3
Tiempo total de entrenamiento: 2.06 minutos
Best model: ../Models_Output_2/Ejex_7_64_8_20_0_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 1.0000  | f1 = 0.1724

Matriz de confusión:
[[ 0 48]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.00      0.00      0.00        48
    Dementia       0.09      1.00      0.17         5

    accuracy                           0.09        53
   macro avg       0.05      0.50      0.09        53
weighted avg       0.01      0.09      0.02        53

✳️ Entrenando modelo Ejex_8_64_8

⏺️ Épocas 20 | LR-WD 0.0008-0.0005 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8465 ||BAC =0.5000 | Recall =1.0000 | AUC=0.4793


>> Early stopping activado 3
Tiempo total de entrenamiento: 2.06 minutos
Best model: ../Models_Output_2/Ejex_8_64_8_20_0_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 1.0000  | f1 = 0.1724

Matriz de confusión:
[[ 0 48]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.00      0.00      0.00        48
    Dementia       0.09      1.00      0.17         5

    accuracy                           0.09        53
   macro avg       0.05      0.50      0.09        53
weighted avg       0.01      0.09      0.02        53

✳️ Entrenando modelo Ejex_9_64_8

⏺️ Épocas 20 | LR-WD 0.0006-0.001 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8188 ||BAC =0.4069 | Recall =0.4000 | AUC=0.4828


>> Mejor modelo guardadoEpoch 2/20 | TrainLoss=0.6758 ||BAC =0.4776 | Recall =0.3000 | AUC=0.4345


>> Early stopping activado 4
Tiempo total de entrenamiento: 2.58 minutos
Best model: ../Models_Output_2/Ejex_9_64_8_20_1_3.pth

 TEST =====
BAC = 0.6562 | AUC = 0.6562 | recall = 1.0000  | f1 = 0.2326

Matriz de confusión:
[[15 33]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.31      0.48        48
    Dementia       0.13      1.00      0.23         5

    accuracy                           0.38        53
   macro avg       0.57      0.66      0.35        53
weighted avg       0.92      0.38      0.45        53

✳️ Entrenando modelo Ejex_10_64_8

⏺️ Épocas 20 | LR-WD 0.0006-0.0008 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8197 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5586


>> Mejor modelo guardadoEpoch 3/20 | TrainLoss=0.5388 ||BAC =0.5724 | Recall =0.8000 | AUC=0.5672


>> Early stopping activado 5
Tiempo total de entrenamiento: 3.10 minutos
Best model: ../Models_Output_2/Ejex_10_64_8_20_2_3.pth

 TEST =====
BAC = 0.5771 | AUC = 0.5771 | recall = 0.8000  | f1 = 0.2000

Matriz de confusión:
[[17 31]
 [ 1  4]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.94      0.35      0.52        48
    Dementia       0.11      0.80      0.20         5

    accuracy                           0.40        53
   macro avg       0.53      0.58      0.36        53
weighted avg       0.87      0.40      0.49        53

✳️ Entrenando modelo Ejex_11_64_8

⏺️ Épocas 20 | LR-WD 0.0006-0.0006 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8354 ||BAC =0.5000 | Recall =1.0000 | AUC=0.4690


>> Mejor modelo guardadoEpoch 4/20 | TrainLoss=0.6964 ||BAC =0.5638 | Recall =0.3000 | AUC=0.4828


>> Early stopping activado 6
Tiempo total de entrenamiento: 3.66 minutos
Best model: ../Models_Output_2/Ejex_11_64_8_20_3_3.pth

 TEST =====
BAC = 0.3438 | AUC = 0.3438 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[33 15]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.87      0.69      0.77        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.62        53
   macro avg       0.43      0.34      0.38        53
weighted avg       0.79      0.62      0.70        53

✳️ Entrenando modelo Ejex_12_64_8

⏺️ Épocas 20 | LR-WD 0.0006-0.0005 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.7721 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4862


>> Early stopping activado 3
Tiempo total de entrenamiento: 2.15 minutos
Best model: ../Models_Output_2/Ejex_12_64_8_20_0_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_13_64_8

⏺️ Épocas 20 | LR-WD 0.0005-0.001 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8807 ||BAC =0.5500 | Recall =0.1000 | AUC=0.5069


>> Early stopping activado 3
Tiempo total de entrenamiento: 2.08 minutos
Best model: ../Models_Output_2/Ejex_13_64_8_20_0_3.pth

 TEST =====
BAC = 0.4896 | AUC = 0.4896 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[47  1]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.90      0.98      0.94        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.89        53
   macro avg       0.45      0.49      0.47        53
weighted avg       0.82      0.89      0.85        53

✳️ Entrenando modelo Ejex_14_64_8

⏺️ Épocas 20 | LR-WD 0.0005-0.0008 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8053 ||BAC =0.5500 | Recall =0.1000 | AUC=0.4621


>> Early stopping activado 3
Tiempo total de entrenamiento: 2.06 minutos
Best model: ../Models_Output_2/Ejex_14_64_8_20_0_3.pth

 TEST =====
BAC = 0.6792 | AUC = 0.6792 | recall = 0.4000  | f1 = 0.4444

Matriz de confusión:
[[46  2]
 [ 3  2]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.94      0.96      0.95        48
    Dementia       0.50      0.40      0.44         5

    accuracy                           0.91        53
   macro avg       0.72      0.68      0.70        53
weighted avg       0.90      0.91      0.90        53

✳️ Entrenando modelo Ejex_15_64_8

⏺️ Épocas 20 | LR-WD 0.0005-0.0006 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.7684 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5138


>> Early stopping activado 3
Tiempo total de entrenamiento: 2.04 minutos
Best model: ../Models_Output_2/Ejex_15_64_8_20_0_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_16_64_8

⏺️ Épocas 20 | LR-WD 0.0005-0.0005 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.7522 ||BAC =0.5000 | Recall =0.0000 | AUC=0.6034


>> Early stopping activado 3
Tiempo total de entrenamiento: 2.09 minutos
Best model: ../Models_Output_2/Ejex_16_64_8_20_0_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53



## Epochs 30, batch 16

In [20]:
# Ejecutar 3
EPOCHS = 30
EARLY = 5
n_slices = 64
BATCH = 16
# ---------------------------
# Ejecutar cada combinación
for i, (LR, WEIGHT) in enumerate(grid, start=1):
    MODELO = f"Ejex_{i}_{n_slices}_{BATCH}"
    main(df, DEVICE, n_slices, EPOCHS, LR, WEIGHT, EARLY, BATCH, MODELO)

✳️ Entrenando modelo Ejex_1_64_16

⏺️ Épocas 30 | LR-WD 0.001-0.001 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.9173 ||BAC =0.5000 | Recall =1.0000 | AUC=0.5759


>> Mejor modelo guardadoEpoch 5/30 | TrainLoss=0.4744 ||BAC =0.5138 | Recall =0.2000 | AUC=0.5310


>> Early stopping activado 9
Tiempo total de entrenamiento: 4.27 minutos
Best model: ../Models_Output_2/Ejex_1_64_16_30_4_5.pth

 TEST =====
BAC = 0.6542 | AUC = 0.6542 | recall = 0.6000  | f1 = 0.2727

Matriz de confusión:
[[34 14]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.94      0.71      0.81        48
    Dementia       0.18      0.60      0.27         5

    accuracy                           0.70        53
   macro avg       0.56      0.65      0.54        53
weighted avg       0.87      0.70      0.76        53

✳️ Entrenando modelo Ejex_2_64_16

⏺️ Épocas 30 | LR-WD 0.001-0.0008 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.9244 ||BAC =0.5000 | Recall =0.0000 | AUC=0.3655


>> Mejor modelo guardadoEpoch 4/30 | TrainLoss=0.5018 ||BAC =0.5172 | Recall =1.0000 | AUC=0.5431


>> Mejor modelo guardadoEpoch 6/30 | TrainLoss=0.4299 ||BAC =0.5724 | Recall =0.8000 | AUC=0.5690


>> Early stopping activado 10
Tiempo total de entrenamiento: 4.93 minutos
Best model: ../Models_Output_2/Ejex_2_64_16_30_5_5.pth

 TEST =====
BAC = 0.5938 | AUC = 0.5938 | recall = 1.0000  | f1 = 0.2041

Matriz de confusión:
[[ 9 39]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.19      0.32        48
    Dementia       0.11      1.00      0.20         5

    accuracy                           0.26        53
   macro avg       0.56      0.59      0.26        53
weighted avg       0.92      0.26      0.31        53

✳️ Entrenando modelo Ejex_3_64_16

⏺️ Épocas 30 | LR-WD 0.001-0.0006 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.8684 ||BAC =0.4500 | Recall =0.9000 | AUC=0.4897


>> Mejor modelo guardadoEpoch 2/30 | TrainLoss=0.6742 ||BAC =0.5000 | Recall =1.0000 | AUC=0.5000


>> Mejor modelo guardadoEpoch 3/30 | TrainLoss=0.6503 ||BAC =0.5966 | Recall =0.4000 | AUC=0.4759


>> Early stopping activado 7
Tiempo total de entrenamiento: 3.57 minutos
Best model: ../Models_Output_2/Ejex_3_64_16_30_2_5.pth

 TEST =====
BAC = 0.6813 | AUC = 0.6813 | recall = 0.8000  | f1 = 0.2667

Matriz de confusión:
[[27 21]
 [ 1  4]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.96      0.56      0.71        48
    Dementia       0.16      0.80      0.27         5

    accuracy                           0.58        53
   macro avg       0.56      0.68      0.49        53
weighted avg       0.89      0.58      0.67        53

✳️ Entrenando modelo Ejex_4_64_16

⏺️ Épocas 30 | LR-WD 0.001-0.0005 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.9388 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5276


>> Early stopping activado 5
Tiempo total de entrenamiento: 2.63 minutos
Best model: ../Models_Output_2/Ejex_4_64_16_30_0_5.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_5_64_16

⏺️ Épocas 30 | LR-WD 0.0008-0.001 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.8825 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5414


>> Mejor modelo guardadoEpoch 3/30 | TrainLoss=0.5732 ||BAC =0.5500 | Recall =0.1000 | AUC=0.4552


>> Early stopping activado 7
Tiempo total de entrenamiento: 3.61 minutos
Best model: ../Models_Output_2/Ejex_5_64_16_30_2_5.pth

 TEST =====
BAC = 0.7792 | AUC = 0.7792 | recall = 0.6000  | f1 = 0.6000

Matriz de confusión:
[[46  2]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.96      0.96      0.96        48
    Dementia       0.60      0.60      0.60         5

    accuracy                           0.92        53
   macro avg       0.78      0.78      0.78        53
weighted avg       0.92      0.92      0.92        53

✳️ Entrenando modelo Ejex_6_64_16

⏺️ Épocas 30 | LR-WD 0.0008-0.0008 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.9532 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4241


>> Mejor modelo guardadoEpoch 6/30 | TrainLoss=0.4887 ||BAC =0.5759 | Recall =0.6000 | AUC=0.4931


>> Mejor modelo guardadoEpoch 10/30 | TrainLoss=0.3533 ||BAC =0.5793 | Recall =0.4000 | AUC=0.6034


>> Early stopping activado 14
Tiempo total de entrenamiento: 6.70 minutos
Best model: ../Models_Output_2/Ejex_6_64_16_30_9_5.pth

 TEST =====
BAC = 0.7229 | AUC = 0.7229 | recall = 0.8000  | f1 = 0.3077

Matriz de confusión:
[[31 17]
 [ 1  4]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.97      0.65      0.78        48
    Dementia       0.19      0.80      0.31         5

    accuracy                           0.66        53
   macro avg       0.58      0.72      0.54        53
weighted avg       0.90      0.66      0.73        53

✳️ Entrenando modelo Ejex_7_64_16

⏺️ Épocas 30 | LR-WD 0.0008-0.0006 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.9088 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5138


>> Early stopping activado 5
Tiempo total de entrenamiento: 2.68 minutos
Best model: ../Models_Output_2/Ejex_7_64_16_30_0_5.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_8_64_16

⏺️ Épocas 30 | LR-WD 0.0008-0.0005 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7663 ||BAC =0.5000 | Recall =0.0000 | AUC=0.3000


>> Mejor modelo guardadoEpoch 2/30 | TrainLoss=0.6673 ||BAC =0.5879 | Recall =0.9000 | AUC=0.5172


>> Early stopping activado 6
Tiempo total de entrenamiento: 3.11 minutos
Best model: ../Models_Output_2/Ejex_8_64_16_30_1_5.pth

 TEST =====
BAC = 0.4458 | AUC = 0.4458 | recall = 0.6000  | f1 = 0.1429

Matriz de confusión:
[[14 34]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.88      0.29      0.44        48
    Dementia       0.08      0.60      0.14         5

    accuracy                           0.32        53
   macro avg       0.48      0.45      0.29        53
weighted avg       0.80      0.32      0.41        53

✳️ Entrenando modelo Ejex_9_64_16

⏺️ Épocas 30 | LR-WD 0.0006-0.001 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7037 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5000


>> Early stopping activado 5
Tiempo total de entrenamiento: 2.65 minutos
Best model: ../Models_Output_2/Ejex_9_64_16_30_0_5.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_10_64_16

⏺️ Épocas 30 | LR-WD 0.0006-0.0008 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.8148 ||BAC =0.5500 | Recall =0.1000 | AUC=0.5345


>> Mejor modelo guardadoEpoch 2/30 | TrainLoss=0.6359 ||BAC =0.6052 | Recall =0.9000 | AUC=0.6448


>> Early stopping activado 6
Tiempo total de entrenamiento: 3.14 minutos
Best model: ../Models_Output_2/Ejex_10_64_16_30_1_5.pth

 TEST =====
BAC = 0.3458 | AUC = 0.3458 | recall = 0.4000  | f1 = 0.0976

Matriz de confusión:
[[14 34]
 [ 3  2]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.82      0.29      0.43        48
    Dementia       0.06      0.40      0.10         5

    accuracy                           0.30        53
   macro avg       0.44      0.35      0.26        53
weighted avg       0.75      0.30      0.40        53

✳️ Entrenando modelo Ejex_11_64_16

⏺️ Épocas 30 | LR-WD 0.0006-0.0006 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7021 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5207


>> Mejor modelo guardadoEpoch 4/30 | TrainLoss=0.6327 ||BAC =0.5328 | Recall =0.1000 | AUC=0.5793


>> Early stopping activado 8
Tiempo total de entrenamiento: 4.24 minutos
Best model: ../Models_Output_2/Ejex_11_64_16_30_3_5.pth

 TEST =====
BAC = 0.7271 | AUC = 0.7271 | recall = 0.6000  | f1 = 0.4000

Matriz de confusión:
[[41  7]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.95      0.85      0.90        48
    Dementia       0.30      0.60      0.40         5

    accuracy                           0.83        53
   macro avg       0.63      0.73      0.65        53
weighted avg       0.89      0.83      0.85        53

✳️ Entrenando modelo Ejex_12_64_16

⏺️ Épocas 30 | LR-WD 0.0006-0.0005 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7095 ||BAC =0.5000 | Recall =1.0000 | AUC=0.4862


>> Mejor modelo guardadoEpoch 3/30 | TrainLoss=0.6557 ||BAC =0.5345 | Recall =1.0000 | AUC=0.4586


>> Early stopping activado 7
Tiempo total de entrenamiento: 3.97 minutos
Best model: ../Models_Output_2/Ejex_12_64_16_30_2_5.pth

 TEST =====
BAC = 0.5208 | AUC = 0.5208 | recall = 1.0000  | f1 = 0.1786

Matriz de confusión:
[[ 2 46]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.04      0.08        48
    Dementia       0.10      1.00      0.18         5

    accuracy                           0.13        53
   macro avg       0.55      0.52      0.13        53
weighted avg       0.91      0.13      0.09        53

✳️ Entrenando modelo Ejex_13_64_16

⏺️ Épocas 30 | LR-WD 0.0005-0.001 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7566 ||BAC =0.5259 | Recall =0.5000 | AUC=0.5069


>> Early stopping activado 5
Tiempo total de entrenamiento: 2.78 minutos
Best model: ../Models_Output_2/Ejex_13_64_16_30_0_5.pth

 TEST =====
BAC = 0.4396 | AUC = 0.4396 | recall = 0.4000  | f1 = 0.1250

Matriz de confusión:
[[23 25]
 [ 3  2]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.88      0.48      0.62        48
    Dementia       0.07      0.40      0.12         5

    accuracy                           0.47        53
   macro avg       0.48      0.44      0.37        53
weighted avg       0.81      0.47      0.57        53

✳️ Entrenando modelo Ejex_14_64_16

⏺️ Épocas 30 | LR-WD 0.0005-0.0008 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.8056 ||BAC =0.5517 | Recall =1.0000 | AUC=0.4103


>> Mejor modelo guardadoEpoch 3/30 | TrainLoss=0.7370 ||BAC =0.5776 | Recall =0.5000 | AUC=0.6621


>> Early stopping activado 7
Tiempo total de entrenamiento: 3.69 minutos
Best model: ../Models_Output_2/Ejex_14_64_16_30_2_5.pth

 TEST =====
BAC = 0.6333 | AUC = 0.6333 | recall = 0.6000  | f1 = 0.2500

Matriz de confusión:
[[32 16]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.94      0.67      0.78        48
    Dementia       0.16      0.60      0.25         5

    accuracy                           0.66        53
   macro avg       0.55      0.63      0.52        53
weighted avg       0.87      0.66      0.73        53

✳️ Entrenando modelo Ejex_15_64_16

⏺️ Épocas 30 | LR-WD 0.0005-0.0006 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.7311 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4759


>> Mejor modelo guardadoEpoch 4/30 | TrainLoss=0.4944 ||BAC =0.5931 | Recall =0.6000 | AUC=0.5414


>> Early stopping activado 8
Tiempo total de entrenamiento: 4.23 minutos
Best model: ../Models_Output_2/Ejex_15_64_16_30_3_5.pth

 TEST =====
BAC = 0.5917 | AUC = 0.5917 | recall = 0.6000  | f1 = 0.2143

Matriz de confusión:
[[28 20]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.93      0.58      0.72        48
    Dementia       0.13      0.60      0.21         5

    accuracy                           0.58        53
   macro avg       0.53      0.59      0.47        53
weighted avg       0.86      0.58      0.67        53

✳️ Entrenando modelo Ejex_16_64_16

⏺️ Épocas 30 | LR-WD 0.0005-0.0005 | Patience 5
▶️ Start train


>> Mejor modelo guardadoEpoch 1/30 | TrainLoss=0.8902 ||BAC =0.5000 | Recall =1.0000 | AUC=0.4724


>> Mejor modelo guardadoEpoch 3/30 | TrainLoss=0.6103 ||BAC =0.5379 | Recall =0.8000 | AUC=0.4655


>> Early stopping activado 7
Tiempo total de entrenamiento: 3.58 minutos
Best model: ../Models_Output_2/Ejex_16_64_16_30_2_5.pth

 TEST =====
BAC = 0.5312 | AUC = 0.5312 | recall = 1.0000  | f1 = 0.1818

Matriz de confusión:
[[ 3 45]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.06      0.12        48
    Dementia       0.10      1.00      0.18         5

    accuracy                           0.15        53
   macro avg       0.55      0.53      0.15        53
weighted avg       0.92      0.15      0.12        53



## Epochs 20, batch 16

In [21]:
# Ejecutar 2
EPOCHS = 20
EARLY = 3
n_slices = 64
BATCH = 16
# ---------------------------
# Ejecutar cada combinación
for i, (LR, WEIGHT) in enumerate(grid, start=1):
    MODELO = f"Ejex_{i}_{n_slices}_{BATCH}"
    main(df, DEVICE, n_slices, EPOCHS, LR, WEIGHT, EARLY, BATCH, MODELO)

✳️ Entrenando modelo Ejex_1_64_16

⏺️ Épocas 20 | LR-WD 0.001-0.001 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.7598 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4828


>> Mejor modelo guardadoEpoch 4/20 | TrainLoss=0.5531 ||BAC =0.5362 | Recall =0.9000 | AUC=0.4310


>> Mejor modelo guardadoEpoch 6/20 | TrainLoss=0.4792 ||BAC =0.5431 | Recall =0.5000 | AUC=0.4759


>> Mejor modelo guardadoEpoch 9/20 | TrainLoss=0.3300 ||BAC =0.5517 | Recall =1.0000 | AUC=0.4483


>> Early stopping activado 11
Tiempo total de entrenamiento: 5.38 minutos
Best model: ../Models_Output_2/Ejex_1_64_16_20_8_3.pth

 TEST =====
BAC = 0.5104 | AUC = 0.5104 | recall = 1.0000  | f1 = 0.1754

Matriz de confusión:
[[ 1 47]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.02      0.04        48
    Dementia       0.10      1.00      0.18         5

    accuracy                           0.11        53
   macro avg       0.55      0.51      0.11        53
weighted avg       0.91      0.11      0.05        53

✳️ Entrenando modelo Ejex_2_64_16

⏺️ Épocas 20 | LR-WD 0.001-0.0008 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8449 ||BAC =0.5000 | Recall =1.0000 | AUC=0.5379


>> Mejor modelo guardadoEpoch 4/20 | TrainLoss=0.5565 ||BAC =0.5345 | Recall =1.0000 | AUC=0.5052


>> Mejor modelo guardadoEpoch 5/20 | TrainLoss=0.5628 ||BAC =0.5517 | Recall =1.0000 | AUC=0.3759


>> Early stopping activado 7
Tiempo total de entrenamiento: 3.58 minutos
Best model: ../Models_Output_2/Ejex_2_64_16_20_4_3.pth

 TEST =====
BAC = 0.5208 | AUC = 0.5208 | recall = 1.0000  | f1 = 0.1786

Matriz de confusión:
[[ 2 46]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.04      0.08        48
    Dementia       0.10      1.00      0.18         5

    accuracy                           0.13        53
   macro avg       0.55      0.52      0.13        53
weighted avg       0.91      0.13      0.09        53

✳️ Entrenando modelo Ejex_3_64_16

⏺️ Épocas 20 | LR-WD 0.001-0.0006 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.7527 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5000


>> Early stopping activado 3
Tiempo total de entrenamiento: 1.81 minutos
Best model: ../Models_Output_2/Ejex_3_64_16_20_0_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_4_64_16

⏺️ Épocas 20 | LR-WD 0.001-0.0005 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.9593 ||BAC =0.5000 | Recall =1.0000 | AUC=0.4138


>> Mejor modelo guardadoEpoch 4/20 | TrainLoss=0.6385 ||BAC =0.5172 | Recall =1.0000 | AUC=0.5069


>> Early stopping activado 6
Tiempo total de entrenamiento: 3.18 minutos
Best model: ../Models_Output_2/Ejex_4_64_16_20_3_3.pth

 TEST =====
BAC = 0.5208 | AUC = 0.5208 | recall = 1.0000  | f1 = 0.1786

Matriz de confusión:
[[ 2 46]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.04      0.08        48
    Dementia       0.10      1.00      0.18         5

    accuracy                           0.13        53
   macro avg       0.55      0.52      0.13        53
weighted avg       0.91      0.13      0.09        53

✳️ Entrenando modelo Ejex_5_64_16

⏺️ Épocas 20 | LR-WD 0.0008-0.001 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8062 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4172


>> Early stopping activado 3
Tiempo total de entrenamiento: 1.84 minutos
Best model: ../Models_Output_2/Ejex_5_64_16_20_0_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_6_64_16

⏺️ Épocas 20 | LR-WD 0.0008-0.0008 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.7733 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4655


>> Mejor modelo guardadoEpoch 3/20 | TrainLoss=0.6152 ||BAC =0.5862 | Recall =1.0000 | AUC=0.3897


>> Early stopping activado 5
Tiempo total de entrenamiento: 2.79 minutos
Best model: ../Models_Output_2/Ejex_6_64_16_20_2_3.pth

 TEST =====
BAC = 0.5312 | AUC = 0.5312 | recall = 1.0000  | f1 = 0.1818

Matriz de confusión:
[[ 3 45]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.06      0.12        48
    Dementia       0.10      1.00      0.18         5

    accuracy                           0.15        53
   macro avg       0.55      0.53      0.15        53
weighted avg       0.92      0.15      0.12        53

✳️ Entrenando modelo Ejex_7_64_16

⏺️ Épocas 20 | LR-WD 0.0008-0.0006 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8483 ||BAC =0.5000 | Recall =1.0000 | AUC=0.4517


>> Early stopping activado 3
Tiempo total de entrenamiento: 1.85 minutos
Best model: ../Models_Output_2/Ejex_7_64_16_20_0_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 1.0000  | f1 = 0.1724

Matriz de confusión:
[[ 0 48]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.00      0.00      0.00        48
    Dementia       0.09      1.00      0.17         5

    accuracy                           0.09        53
   macro avg       0.05      0.50      0.09        53
weighted avg       0.01      0.09      0.02        53

✳️ Entrenando modelo Ejex_8_64_16

⏺️ Épocas 20 | LR-WD 0.0008-0.0005 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.6801 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5034


>> Early stopping activado 3
Tiempo total de entrenamiento: 1.84 minutos
Best model: ../Models_Output_2/Ejex_8_64_16_20_0_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_9_64_16

⏺️ Épocas 20 | LR-WD 0.0006-0.001 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.6447 ||BAC =0.4828 | Recall =0.0000 | AUC=0.4276


>> Mejor modelo guardadoEpoch 2/20 | TrainLoss=0.7181 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4966


>> Early stopping activado 4
Tiempo total de entrenamiento: 2.32 minutos
Best model: ../Models_Output_2/Ejex_9_64_16_20_1_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_10_64_16

⏺️ Épocas 20 | LR-WD 0.0006-0.0008 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.6931 ||BAC =0.5000 | Recall =0.0000 | AUC=0.4586


>> Early stopping activado 3
Tiempo total de entrenamiento: 1.84 minutos
Best model: ../Models_Output_2/Ejex_10_64_16_20_0_3.pth

 TEST =====
BAC = 0.4896 | AUC = 0.4896 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[47  1]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.90      0.98      0.94        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.89        53
   macro avg       0.45      0.49      0.47        53
weighted avg       0.82      0.89      0.85        53

✳️ Entrenando modelo Ejex_11_64_16

⏺️ Épocas 20 | LR-WD 0.0006-0.0006 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.7774 ||BAC =0.6310 | Recall =0.4000 | AUC=0.5552


>> Early stopping activado 3
Tiempo total de entrenamiento: 1.86 minutos
Best model: ../Models_Output_2/Ejex_11_64_16_20_0_3.pth

 TEST =====
BAC = 0.6229 | AUC = 0.6229 | recall = 0.6000  | f1 = 0.2400

Matriz de confusión:
[[31 17]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.94      0.65      0.77        48
    Dementia       0.15      0.60      0.24         5

    accuracy                           0.64        53
   macro avg       0.54      0.62      0.50        53
weighted avg       0.86      0.64      0.72        53

✳️ Entrenando modelo Ejex_12_64_16

⏺️ Épocas 20 | LR-WD 0.0006-0.0005 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.7773 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5517


>> Early stopping activado 3
Tiempo total de entrenamiento: 1.85 minutos
Best model: ../Models_Output_2/Ejex_12_64_16_20_0_3.pth

 TEST =====
BAC = 0.5000 | AUC = 0.5000 | recall = 0.0000  | f1 = 0.0000

Matriz de confusión:
[[48  0]
 [ 5  0]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.91      1.00      0.95        48
    Dementia       0.00      0.00      0.00         5

    accuracy                           0.91        53
   macro avg       0.45      0.50      0.48        53
weighted avg       0.82      0.91      0.86        53

✳️ Entrenando modelo Ejex_13_64_16

⏺️ Épocas 20 | LR-WD 0.0005-0.001 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.7356 ||BAC =0.5000 | Recall =0.0000 | AUC=0.3345


>> Mejor modelo guardadoEpoch 3/20 | TrainLoss=0.4528 ||BAC =0.6276 | Recall =0.6000 | AUC=0.6069


>> Early stopping activado 5
Tiempo total de entrenamiento: 2.81 minutos
Best model: ../Models_Output_2/Ejex_13_64_16_20_2_3.pth

 TEST =====
BAC = 0.4813 | AUC = 0.4813 | recall = 0.4000  | f1 = 0.1429

Matriz de confusión:
[[27 21]
 [ 3  2]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.90      0.56      0.69        48
    Dementia       0.09      0.40      0.14         5

    accuracy                           0.55        53
   macro avg       0.49      0.48      0.42        53
weighted avg       0.82      0.55      0.64        53

✳️ Entrenando modelo Ejex_14_64_16

⏺️ Épocas 20 | LR-WD 0.0005-0.0008 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.7153 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5655


>> Mejor modelo guardadoEpoch 3/20 | TrainLoss=0.8269 ||BAC =0.5500 | Recall =0.1000 | AUC=0.4862


>> Early stopping activado 5
Tiempo total de entrenamiento: 2.72 minutos
Best model: ../Models_Output_2/Ejex_14_64_16_20_2_3.pth

 TEST =====
BAC = 0.7583 | AUC = 0.7583 | recall = 0.6000  | f1 = 0.5000

Matriz de confusión:
[[44  4]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.96      0.92      0.94        48
    Dementia       0.43      0.60      0.50         5

    accuracy                           0.89        53
   macro avg       0.69      0.76      0.72        53
weighted avg       0.91      0.89      0.90        53

✳️ Entrenando modelo Ejex_15_64_16

⏺️ Épocas 20 | LR-WD 0.0005-0.0006 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.7660 ||BAC =0.5000 | Recall =0.0000 | AUC=0.5138


>> Mejor modelo guardadoEpoch 2/20 | TrainLoss=0.5968 ||BAC =0.5276 | Recall =0.4000 | AUC=0.4517


>> Mejor modelo guardadoEpoch 4/20 | TrainLoss=0.5805 ||BAC =0.5517 | Recall =1.0000 | AUC=0.5414


>> Early stopping activado 6
Tiempo total de entrenamiento: 3.27 minutos
Best model: ../Models_Output_2/Ejex_15_64_16_20_3_3.pth

 TEST =====
BAC = 0.5104 | AUC = 0.5104 | recall = 1.0000  | f1 = 0.1754

Matriz de confusión:
[[ 1 47]
 [ 0  5]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       1.00      0.02      0.04        48
    Dementia       0.10      1.00      0.18         5

    accuracy                           0.11        53
   macro avg       0.55      0.51      0.11        53
weighted avg       0.91      0.11      0.05        53

✳️ Entrenando modelo Ejex_16_64_16

⏺️ Épocas 20 | LR-WD 0.0005-0.0005 | Patience 3
▶️ Start train


>> Mejor modelo guardadoEpoch 1/20 | TrainLoss=0.8418 ||BAC =0.5000 | Recall =0.0000 | AUC=0.2552


>> Mejor modelo guardadoEpoch 3/20 | TrainLoss=0.6533 ||BAC =0.5017 | Recall =0.9000 | AUC=0.4310


>> Early stopping activado 5
Tiempo total de entrenamiento: 2.80 minutos
Best model: ../Models_Output_2/Ejex_16_64_16_20_2_3.pth

 TEST =====
BAC = 0.3000 | AUC = 0.3000 | recall = 0.6000  | f1 = 0.1071

Matriz de confusión:
[[ 0 48]
 [ 2  3]]

Reporte de clasificación:
              precision    recall  f1-score   support

 No Dementia       0.00      0.00      0.00        48
    Dementia       0.06      0.60      0.11         5

    accuracy                           0.06        53
   macro avg       0.03      0.30      0.05        53
weighted avg       0.01      0.06      0.01        53

